<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Personal Access Client
    |--------------------------------------------------------------------------
    |
    | Sanctum can use personal access tokens to authenticate requests. The token
    | issuer model used to issue these tokens can be configured here. If you
    | would like to use a different model, you may specify it here.
    |
    */

    'personal_access' => [
        'provider' => 'users',
        'table' => 'personal_access_tokens',
    ],

    /*
    |--------------------------------------------------------------------------
    | Expiration Minutes
    |--------------------------------------------------------------------------
    |
    | This value controls the number of minutes until an issued token becomes
    | invalid and will not be able to be used. A higher value keeps tokens
    | valid for a longer period of time, but provides less security.
    |
    */

    'expiration' => null,

    /*
    |--------------------------------------------------------------------------
    | Token Prefix
    |--------------------------------------------------------------------------
    |
    | Sanctum can prefix each issued token with a custom string that you may
    | specify. This helps to visually distinguish tokens generated by your
    | application from other tokens that may be present in the database.
    |
    */

    'token_prefix' => env('SANCTUM_TOKEN_PREFIX', ''),

    /*
    |--------------------------------------------------------------------------
    | Authentication Middleware
    |--------------------------------------------------------------------------
    |
    | Sanctum can register its authentication middleware with Laravel. The
    | middleware that is registered can be configured here. If this value
    | is set to "null", Sanctum will not register its middleware.
    |
    */

    'middleware' => [
        'auth' => env('SANCTUM_AUTHENTICATION_MIDDLEWARE', 'auth'),
        'verify_csrf_token' => env('SANCTUM_VERIFY_CSRF_TOKEN_MIDDLEWARE', \App\Http\Middleware\VerifyCsrfToken::class),
    ],

];
