<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Payment Receipt #{{ $payment->payment_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #333; }
        .header { border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
        .header h1 { font-size: 24px; margin: 0; color: #000; }
        .header p { margin: 2px 0; font-size: 11px; color: #666; }
        .details { width: 100%; margin-bottom: 20px; }
        .details td { vertical-align: top; padding: 4px 8px; font-size: 11px; }
        .details .label { font-weight: bold; color: #555; width: 140px; }
        table.allocations { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table.allocations th { background: #333; color: #fff; padding: 8px; font-size: 10px; text-align: left; text-transform: uppercase; }
        table.allocations td { padding: 6px 8px; border-bottom: 1px solid #ddd; font-size: 11px; }
        table.allocations .right { text-align: right; }
        table.allocations tr:nth-child(even) { background: #f9f9f9; }
        .totals { width: 300px; margin-left: auto; }
        .totals td { padding: 4px 8px; font-size: 11px; }
        .totals .label { text-align: right; font-weight: bold; }
        .totals .value { text-align: right; width: 100px; }
        .totals .grand { font-size: 14px; font-weight: bold; border-top: 2px solid #333; }
        .footer { position: fixed; bottom: 20px; left: 0; right: 0; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Payment Receipt</h1>
        <p>Receipt #: {{ $payment->payment_number }}</p>
        <p>Date: {{ $payment->payment_date ? date('d/m/Y', strtotime($payment->payment_date)) : '' }}</p>
        <p>Status: {{ ucfirst($payment->status ?? 'approved') }}</p>
    </div>

    <table class="details">
        <tr>
            <td class="label">Customer:</td>
            <td>{{ $payment->customer->name ?? 'N/A' }}</td>
            <td class="label">Reference:</td>
            <td>{{ $payment->reference ?: '-' }}</td>
        </tr>
        <tr>
            <td class="label">Bank Account:</td>
            <td>{{ $payment->bankAccount->account_name ?? 'N/A' }}</td>
            <td class="label">Currency:</td>
            <td>{{ $payment->currency ?? 'USD' }}</td>
        </tr>
        @if($payment->memo)
        <tr>
            <td class="label">Memo:</td>
            <td colspan="3">{{ $payment->memo }}</td>
        </tr>
        @endif
    </table>

    @if($payment->allocations->count())
    <table class="allocations">
        <thead>
            <tr>
                <th>Invoice #</th>
                <th class="right">Invoice Amount</th>
                <th class="right">Allocated</th>
                <th class="right">Discount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($payment->allocations as $alloc)
            <tr>
                <td>{{ $alloc->salesOrder->order_number ?? '#' . $alloc->sales_order_id }}</td>
                <td class="right">{{ number_format($alloc->salesOrder->total_amount ?? 0, 2) }}</td>
                <td class="right">{{ number_format($alloc->amount, 2) }}</td>
                <td class="right">{{ number_format($alloc->discount, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <table class="totals">
        <tr>
            <td class="label">Amount Received:</td>
            <td class="value">{{ number_format($payment->amount, 2) }}</td>
        </tr>
        @if($payment->discount > 0)
        <tr>
            <td class="label">Discount:</td>
            <td class="value">{{ number_format($payment->discount, 2) }}</td>
        </tr>
        @endif
        @if($payment->bank_charge > 0)
        <tr>
            <td class="label">Bank Charge:</td>
            <td class="value">{{ number_format($payment->bank_charge, 2) }}</td>
        </tr>
        @endif
        <tr class="grand">
            <td class="label">Bank Amount:</td>
            <td class="value">{{ number_format($payment->bank_amount, 2) }}</td>
        </tr>
    </table>

    <div class="footer">
        Payment Receipt #{{ $payment->payment_number }} &mdash; Generated by FA-SAAS
    </div>
</body>
</html>
