<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Delivery Note #{{ $delivery->order_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #333; }
        .header { border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
        .header h1 { font-size: 24px; margin: 0; color: #000; }
        .header p { margin: 2px 0; font-size: 11px; color: #666; }
        .details { width: 100%; margin-bottom: 20px; }
        .details td { vertical-align: top; padding: 4px 8px; font-size: 11px; }
        .details .label { font-weight: bold; color: #555; width: 140px; }
        table.items { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table.items th { background: #333; color: #fff; padding: 8px; font-size: 10px; text-align: left; text-transform: uppercase; }
        table.items td { padding: 6px 8px; border-bottom: 1px solid #ddd; font-size: 11px; }
        table.items .right { text-align: right; }
        table.items tr:nth-child(even) { background: #f9f9f9; }
        .totals { width: 300px; margin-left: auto; }
        .totals td { padding: 4px 8px; font-size: 11px; }
        .totals .label { text-align: right; font-weight: bold; }
        .totals .value { text-align: right; width: 100px; }
        .footer { position: fixed; bottom: 20px; left: 0; right: 0; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Delivery Note</h1>
        <p>Delivery #: {{ $delivery->order_number }}</p>
        <p>Date: {{ $delivery->delivery_date ? date('d/m/Y', strtotime($delivery->delivery_date)) : date('d/m/Y') }}</p>
        <p>Status: Delivered</p>
    </div>

    <table class="details">
        <tr>
            <td class="label">Customer:</td>
            <td>{{ $delivery->customer->name ?? 'N/A' }}</td>
            <td class="label">Reference:</td>
            <td>{{ $delivery->internal_notes ?? '-' }}</td>
        </tr>
        @if($delivery->delivery_address)
        <tr>
            <td class="label">Delivery Address:</td>
            <td colspan="3">{{ $delivery->delivery_address }}</td>
        </tr>
        @endif
        <tr>
            <td class="label">Location:</td>
            <td>{{ $delivery->location ?? 'N/A' }}</td>
            <td class="label">Sales Person:</td>
            <td>{{ $delivery->salesPerson->name ?? 'N/A' }}</td>
        </tr>
    </table>

    <table class="items">
        <thead>
            <tr>
                <th style="width:50px">#</th>
                <th>Item Code</th>
                <th>Description</th>
                <th class="right">Quantity</th>
            </tr>
        </thead>
        <tbody>
            @php $i = 1; @endphp
            @foreach($delivery->lineItems as $item)
                <tr>
                    <td>{{ $i++ }}</td>
                    <td>{{ $item->item_code }}</td>
                    <td>{{ $item->description }}</td>
                    <td class="right">{{ number_format($item->quantity, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    @if($delivery->customer_notes)
    <div style="margin-top: 30px;">
        <strong>Notes:</strong>
        <p style="margin-top: 5px;">{{ $delivery->customer_notes }}</p>
    </div>
    @endif

    <div class="footer">
        Delivery Note #{{ $delivery->order_number }} &mdash; Generated by FA-SAAS
    </div>
</body>
</html>
